# Hybrid model(knn+svm)

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

In [2]:
data = pd.read_csv("new_Features.csv")

In [3]:
data

tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
...                 ...                ...                ...   
7347           0.299665          -0.057193          -0.181233   
7348           0.273853          -0.007749          -0.147468   
7349           0.273387          -0.017011          -0.045022   
7350           0.289654          -0.018843          -0.158281   
7351           0.351503          -0.012423          -0.203867   

      tBodyAcc-std()-X  tBodyAcc-std()-Y  tBodyAcc-std()-Z  tBodyAcc-mad()-X  \
0            -0.995279         -0.983111         -0.913526         -0.995112   
1            -0.998245         -0.975300         -0.960322         -0.998807   
2            -0.995380         -0.967187         -0.978944         -0.996520   
3            -0.996091         -0.983403         -0.990675         -0.997099   
4            -0.998139         -0.980817         -0.990482         -0.998321   
...                ...               ...               ...               ...   
7347         -0.195387          0.039905          0.077078         -0.282301   
7348         -0.235309          0.004816          0.059280         -0.322552   
7349         -0.218218         -0.103822          0.274533         -0.304515   
7350         -0.219139         -0.111412          0.268893         -0.310487   
7351         -0.269270         -0.087212          0.177404         -0.377404   

      tBodyAcc-mad()-Y  tBodyAcc-mad()-Z  tBodyAcc-max()-X  ...  \
0            -0.983185         -0.923527         -0.934724  ...   
1            -0.974914         -0.957686         -0.943068  ...   
2            -0.963668         -0.977469         -0.938692  ...   
3            -0.982750         -0.989302         -0.938692  ...   
4            -0.979672         -0.990441         -0.942469  ...   
...                ...               ...               ...  ...   
7347          0.043616          0.060410          0.210795  ...   
7348         -0.029456          0.080585          0.117440  ...   
7349         -0.098913          0.332584          0.043999  ...   
7350         -0.068200          0.319473          0.101702  ...   
7351         -0.038678          0.229430          0.269013  ...   

      tBodyGyro-energy()-X  tBodyGyro-energy()-Y  tBodyGyro-energy()-Z  \
0                -0.999578             -0.999354             -0.999763   
1                -0.999756             -0.999897             -0.999822   
2                -0.999693             -0.999828             -0.999822   
3                -0.999793             -0.999902             -0.999877   
4                -0.999849             -0.999952             -0.999844   
...                    ...                   ...                   ...   
7347             -0.834173             -0.419947             -0.677083   
7348             -0.861977             -0.405579             -0.693805   
7349             -0.801509             -0.305023             -0.747991   
7350             -0.806782             -0.298515             -0.761528   
7351             -0.862321             -0.474331             -0.717200   

      tBodyGyro-iqr()-X  tBodyGyro-iqr()-Y  tBodyGyro-iqr()-Z  \
0             -0.983438          -0.978614          -0.992966   
1             -0.992833          -0.989345          -0.990240   
2             -0.972354          -0.995144          -0.986831   
3             -0.991031          -0.994165          -0.994582   
4             -0.989813          -0.993337          -0.991155   
...                 ...                ...                ...   
7347          -0.451959           0.019043          -0.419986   
7348          -0.402785           0.023374        

In [4]:
# label Encoding 
from sklearn.preprocessing import LabelEncoder
label_encode= LabelEncoder()
data["Activity_code"]=label_encode.fit_transform(data["Activity"])
data1=data.drop("Activity",axis=1)  # Removing the activity colum with label and assigning in new variable


In [5]:
data["Activity_code"].value_counts()

0    1407
2    1374
1    1286
3    1226
5    1073
4     986
Name: Activity_code, dtype: int64

In [6]:
# Splitting the data into x, y 
x=data1.iloc[:,:-1]
y=data1.iloc[:,-1:]


In [7]:
from sklearn.model_selection import train_test_split
Train_X,Test_X,Train_Y,Test_Y=train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
# buliding one model 
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier
estimators = []
model1=SVC(C=1.0, kernel='poly', degree=4,tol=0.001)
estimators.append(("SVC",model1))

model2=KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='auto', leaf_size=30, p=2, metric='minkowski')
estimators.append(("KNN",model2))

ensemble=VotingClassifier(estimators)


In [9]:
hybrid=ensemble.fit(Train_X,np.ravel(Train_Y,order="c")) # np.ravel is used to convert multi row  array into 1d with nothing chnged

In [10]:
hybrid_pred=hybrid.predict(Test_X.values)


C:\Users\deepa\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
C:\Users\deepa\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\deepa\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:110: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\deepa\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 217, in _count_physical_cores
    raise ValueError(


In [11]:
from sklearn import metrics
print("Accuracy : {:.4f}".format(metrics.accuracy_score(Test_Y,hybrid_pred)))

Accuracy : 0.7893


In [12]:
from sklearn.metrics import confusion_matrix,f1_score,recall_score,precision_score

In [13]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(Test_Y,hybrid_pred)
report = classification_report(Test_Y,hybrid_pred)
confusion = confusion_matrix(Test_Y,hybrid_pred)

print(f'Accuracy: {accuracy}')
print(f'Classification Report:\n{report}')
print(f'Confusion Matrix:\n{confusion}')

Accuracy: 0.7892590074779062
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.80      0.74       285
           1       0.66      0.67      0.66       275
           2       0.78      0.63      0.70       278
           3       0.85      0.99      0.91       244
           4       0.93      0.94      0.94       196
           5       0.99      0.77      0.86       193

    accuracy                           0.79      1471
   macro avg       0.81      0.80      0.80      1471
weighted avg       0.80      0.79      0.79      1471

Confusion Matrix:
[[228  37  20   0   0   0]
 [ 63 184  28   0   0   0]
 [ 44  59 175   0   0   0]
 [  0   0   0 242   0   2]
 [  0   0   0  12 184   0]
 [  0   0   0  32  13 148]]


In [14]:
from sklearn.metrics import roc_curve ,roc_auc_score
from sklearn.preprocessing import label_binarize
from itertools import cycle


In [21]:
#  first calculate  fpr tpr and threshold 
y=label_binarize(y,classes=[0,1,2,3,4,5])
n_class=y.shape[1]

In [22]:
n_class

6

In [23]:
y_score = ensemble.fit(Train_X,Train_Y).decision_function(X_test)

C:\Users\deepa\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\deepa\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


AttributeError: 'VotingClassifier' object has no attribute 'decision_function'